### ISSUE TITLE
bigip_asm_policy_fetch wrong param in the example 

### ISSUE THREAD

**Issue by tizianorosato** [f5devcentral/ansible-role-f5ansible#1]
Just noticed that module's examples use "dst" as the destination parameter while the correct one is "dest".

EXAMPLES = r'''
- name: Export policy in binary format
  bigip_asm_policy_fetch:
    name: foobar
    file: export_foo
    dst: /root/download
    binary: yes
    provider:
      password: secret
      server: lb.mydomain.com
      user: admin
  delegate_to: localhost

**Comment by wojtek0806** [comment]
should be fixed already
