### ISSUE TITLE
Issue with ansible-role-f5ansible/tasks/setup.yaml

### ISSUE THREAD

**Issue by rdtechie** [f5devcentral/ansible-role-f5ansible#7]
At my customer we're encountering problems due to the fact that we install roles in a shared folder, and we point roles_path to that folder. But because ansible_facts is looking for setup.py, it first finds the file `ansible-role-f5ansible/tasks/setup.yaml`. This issue is also explained here: https://github.com/ansible/ansible/issues/20702

When we name that particular file to something else, then the issue is resolved. Can you maybe rename this file to something else?

**Comment by rdtechie** [comment]
Anybody?

**Comment by rdtechie** [comment]
Not much activity here...

**Comment by wojtek0806** [comment]
this role is a wrapper around devel code, and used only for that purpose, we do not actively monitor this for that reason, f5ansible is the right repo to raise issues with the role :) I have changed the file for now, as it is not used 'yet'
